plugins {
    id 'com.android.application' version '8.5.2'
}

android {
    namespace 'gr.geekon.labels'
    compileSdk 34

    defaultConfig {
        applicationId "gr.geekon.labels"
        minSdk 21
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
            // υπογραφή debug ώστε το APK να εγκαθίσταται χωρίς keystore
            signingConfig signingConfigs.debug
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
